import { MusicalEvent } from './types';

export const INITIAL_EVENTS: MusicalEvent[] = [
  {
    id: 'sonora-festival',
    name: 'SONORA Festival 2026',
    venue: 'Masseria Capece',
    location: 'Cisternino (Brindisi), Puglia',
    coordinates: { x: 72, y: 75 },
    date: '17 - 19 Luglio 2026',
    timestamp: new Date('2026-07-17').getTime(),
    genre: 'Melodic Techno / Organic House',
    lineup: ['Dixon', 'Satori (Live)', 'Rampue', 'Oceanvs Orientalis', 'Acid Pauli', 'Nu', 'Mira', 'Local Selectors', 'Giuseppe Russo', 'Vera'],
    description: 'Un rituale musicale straordinario incastonato nel magico frutteto monumentale e nella corte storica di Masseria Capece. Sonora Festival celebra la fusione d\'avanguardia tra beat lenti, installazioni scenografiche immerse nella macchia mediterranea e produzioni luce ecosostenibili sotto le stelle pugliesi.',
    status: 'Tickets Available',
    priceRange: '€45 All Pass',
    vibe: 'Masseria Orchard, Organic Deep Beats, Slow Rave, Lights',
    trackSample: {
      title: 'Capece Sunset',
      artist: 'Satori',
      bpm: 118,
      genre: 'Organic House'
    }
  },
  {
    id: 'vox-marmoris',
    name: 'VOX MARMORIS',
    venue: 'Cave di Marmo di Carrara',
    location: 'Carrara, Toscana',
    coordinates: { x: 31, y: 38 },
    date: '24 - 25 Luglio 2026',
    timestamp: new Date('2026-07-24').getTime(),
    genre: 'Electronic / Industrial Art',
    lineup: ['Silent Guest', 'Resident Live', 'Local Artists & Performers', 'Carrara Synth Collective', 'Marmo Drummers', 'Elena Grimaldi'],
    description: 'Un festival unico ed evocativo ospitato direttamente nelle spettacolari cave di marmo bianco di Carrara. La fusione primordiale tra la pietra secolare scolpita, installazioni luminose d\'avanguardia e sonorità elettroniche profonde crea un\'atmosfera impareggiabile.',
    status: 'Tickets Available',
    priceRange: '€70 All Pass',
    vibe: 'White Marble Cave, Mystical Laser Show, Analog Sounds',
    isFavorite: true,
    trackSample: {
      title: 'Marble Symphony',
      artist: 'Vox Resident',
      bpm: 125,
      genre: 'Deep Techno'
    }
  },
  {
    id: 'iperibleo',
    name: 'IPERIBLEO Festival',
    venue: 'Monti Iblei (Patrimonio UNESCO)',
    location: 'Palazzolo Acreide, Sicilia',
    coordinates: { x: 32, y: 102 },
    date: '31 Luglio - 02 Agosto 2026',
    timestamp: new Date('2026-07-31').getTime(),
    genre: 'Performative Music & Arts',
    lineup: ['Experimental Live', 'Ambient Ensembles', 'Visual Performers', 'Alessandro Cortini', 'Lorenzo Senni', 'Simona Cardone'],
    description: 'Ospitato nello splendido scenario dei Monti Iblei a Palazzolo Acreide, patrimonio UNESCO. Iperibleo unisce con eleganza design acustico d\'avanguardia, arti performative e musica elettronica sperimentale in un contesto di immenso valore storico.',
    status: 'Selling Fast',
    priceRange: '€55 Full Pass',
    vibe: 'UNESCO Heritage Site, Intimate Performance, Cultural Art',
    trackSample: {
      title: 'Monti Iblei Wind',
      artist: 'Acoustic Experiment',
      bpm: 118,
      genre: 'Experimental Ambient'
    }
  },
  {
    id: 'no-art-puglia',
    name: 'No Art Puglia Showcase',
    venue: 'Parco Archeologico di Egnazia',
    location: 'Fasano (Brindisi), Puglia',
    coordinates: { x: 74, y: 74 },
    date: '01 Agosto 2026',
    timestamp: new Date('2026-08-01').getTime(),
    genre: 'Minimal House / Deep Tech',
    lineup: ['Adam Port', 'ANOTR', 'Benja', 'Megatronic', 'Luuk van Dijk', 'Toman', 'Prunk', 'Kolter', 'Seta Support'],
    description: 'Il celebre collettivo di Amsterdam "No Art" si insedia nel maestoso Parco Archeologico di Egnazia a Fasano. Immagina giganti di pietra millenaria, muretti a secco e un portale monumentale fuso nel groove trascinante di artisti del calibro di Adam Port e ANOTR. Alloggio consigliato: Masseria Fragnale.',
    status: 'Selling Fast',
    priceRange: '€80 Entry',
    vibe: 'Archaeological Ruins, Sunset Grooves, Monumental Art',
    isFavorite: true,
    trackSample: {
      title: 'Relax My Eyes',
      artist: 'ANOTR',
      bpm: 126,
      genre: 'Minimal House'
    }
  },
  {
    id: 'viva-festival',
    name: 'VIVA! Festival 2026',
    venue: 'Valle d\'Itria TBA Arena',
    location: 'Locorotondo, Puglia',
    coordinates: { x: 73, y: 77 },
    date: '02 Agosto 2026',
    timestamp: new Date('2026-08-02').getTime(),
    genre: 'Avant-garde Pop / Electronic',
    lineup: ['International Guests', 'Live Synth Bands', 'Underground DJ set', 'Gilles Peterson', 'Kode9', 'Puglia Soundclash'],
    description: 'L\'immancabile rito estivo della Valle d\'Itria ritorna a dipingere di sonorità elettroniche futuristiche il cuore rurale della Puglia. Tra storici trulli e uliveti, un festival che combina il sapore della terra con vibrazioni dal mondo.',
    status: 'Tickets Available',
    priceRange: '€40 Standard',
    vibe: 'Trulli Landscape, International Vibes, Multi-stage',
    isFavorite: true,
    trackSample: {
      title: 'Itria Valley Echo',
      artist: 'Viva Collective',
      bpm: 122,
      genre: 'Electronic'
    }
  },
  {
    id: 'masseria-wave',
    name: 'MASSERIA WAVE',
    venue: 'Masseria Lequile',
    location: 'Lequile (Lecce), Puglia',
    coordinates: { x: 78, y: 86 },
    date: '06 Agosto 2026',
    timestamp: new Date('2026-08-06').getTime(),
    genre: 'House / Disco Nights',
    lineup: ['Severino (Horse Meat Disco)', 'Whodamanny', 'Mads', 'DJ Ralf', 'Gallo', 'Lillo'],
    description: 'Una serata indimenticabile nelSalento. Masseria Wave porta a Lequile un party bollente capitanato da Severino ed esponenti della disco nostrana. Totalmente gratuito fino a mezzanotte, per iniziare il weekend di agosto col ritmo giusto a bordo piscina.',
    status: 'Free Entry',
    priceRange: 'Gratis fino a 00:00',
    vibe: 'Salento Pool Party, Energetic Disco, Summer Chill',
    isFavorite: true,
    trackSample: {
      title: 'Salento Nights (Severino Remix)',
      artist: 'Horse Meat Disco Crew',
      bpm: 120,
      genre: 'Nu-Disco'
    }
  },
  {
    id: 'crx-festival',
    name: 'CRX Fest & Bus Shuttle',
    venue: 'Masseria Grottaglie',
    location: 'Grottaglie, Puglia',
    coordinates: { x: 76, y: 79 },
    date: '07 & 08 Agosto 2026',
    timestamp: new Date('2026-08-07').getTime(),
    genre: 'Underground Techno',
    lineup: ['Heavyweight DJ', 'Acid Synth Live', 'Salento Soundsystem', 'Perc', 'Anetha', 'Claudio TPR'],
    description: 'Due giorni consecutivi di bassi telluriche nelle campagne di Grottaglie. CRX Festival offre un pacchetto speciale con navetta shuttle per connettere la masseria residenziale alle dancefloor sotterranee. Per cuori duri e amanti del sound analogico.',
    status: 'Tickets Available',
    priceRange: '€58 Ticket + €70 Masseria',
    vibe: 'Techno Camping, Bus Shuttle Connect, Industrial Masseria',
    isFavorite: true,
    trackSample: {
      title: 'Grottaglie Warehouse',
      artist: 'CRX Live Set',
      bpm: 130,
      genre: 'Acid Techno'
    }
  },
  {
    id: 'zamna-sardinia',
    name: 'Zamna Festival Sardinia',
    venue: 'Phi Beach Club',
    location: 'Baja Sardinia, Sardegna',
    coordinates: { x: 20, y: 64 },
    date: '08 Agosto 2026',
    timestamp: new Date('2026-08-08').getTime(),
    genre: 'Melodic Techno / Progressive',
    lineup: ['Tale Of Us', 'Fideles', 'Massano', 'Oona Dahl', 'Kevin de Vries', 'KAS:ST', 'Colyn', 'Innellea'],
    description: 'Zamna unisce le forze con Phi Beach per un party suggestivo a picco sulle scogliere della Costa Smeralda. Con visual psichedelici e un sound melodico profondo, la serata si snoda dal tramonto dorato fino a notte fonda cullati dalle onde del mare.',
    status: 'Tickets Available',
    priceRange: '€60 - €120',
    vibe: 'Cliffside Sunset, High Fashion, Futuristic Visuals',
    trackSample: {
      title: 'The Sign',
      artist: 'Tale Of Us & CamelPhat',
      bpm: 124,
      genre: 'Melodic Techno'
    }
  },
  {
    id: 'circoloco-grottella',
    name: 'Circoloco Puglia 2026',
    venue: 'Masseria Grottella',
    location: 'Grottaglie, Puglia',
    coordinates: { x: 75, y: 81 },
    date: '14 Agosto 2026',
    timestamp: new Date('2026-08-14').getTime(),
    genre: 'Underground Tech House',
    lineup: ['Seth Troxler', 'Tania Vulcano', 'PAWSA', 'The Martinez Brothers', 'DJ Tennis', 'Carlita', 'Rampa', 'Mochakk', 'Chloé Caillet'],
    description: 'L\'iconico party rosso del DC10 Ibiza fa tappa fissa nel tacco d\'Italia. Circoloco porta un\'ondata di pura energia house e techno underground tra i secolari ulivi di Masseria Grottella, richiamando appassionati da tutt\'Europa.',
    status: 'Selling Fast',
    priceRange: '€50 - €80',
    vibe: 'Wild Vibes, Ibiza Atmosphere, Red Neon Theme',
    trackSample: {
      title: 'Room Service',
      artist: 'PAWSA',
      bpm: 127,
      genre: 'Tech House'
    }
  },
  {
    id: 'opera-festival',
    name: 'OPERA Festival Etna',
    venue: 'Milo Village (Etna Slope)',
    location: 'Milo, Sicilia',
    coordinates: { x: 34, y: 96 },
    date: '20 - 23 Agosto 2026',
    timestamp: new Date('2026-08-20').getTime(),
    genre: 'Electronic Eco-Summit',
    lineup: ['Ambient Masters', 'Modular Synthesizers', 'Psychedelic Electronic', 'Suzanne Ciani', 'Caterina Barbieri', 'Etna Echoes'],
    description: 'Un rituale musicale immerso tra i fitti vigneti vulcanici e le vecchie pinete del vulcano Etna a Milo. Quattro giorni di campeggio naturalistico, laboratori sostenibili ed esibizioni modulari magiche sotto la lava solidificata.',
    status: 'Tickets Available',
    priceRange: '€200 Pass + Camp',
    vibe: 'Volcanic Forest, Natural Eco-Festival, Cosmic Healing',
    trackSample: {
      title: 'Etna Sub-Bass Rhythms',
      artist: 'Opera Resident',
      bpm: 120,
      genre: 'Modular Techno'
    }
  },
  {
    id: 'badawi-puglia',
    name: 'BADAWI Puglia Special',
    venue: 'Fasano Beach Oasis',
    location: 'Fasano, Puglia',
    coordinates: { x: 74, y: 72 },
    date: '22 Agosto 2026',
    timestamp: new Date('2026-08-22').getTime(),
    genre: 'Ethnic House / Tribal Tech',
    lineup: ['Bedouin DJ collectives', 'Tribal Percussionists', 'Local Selector', 'Damian Lazarus', 'Black Coffee', 'Blond:ish', 'Goldminds'],
    description: 'Badawi sbarca a Fasano per una notte imperniata su sonorità desertiche, percussioni sciamaniche dal vivo e caldi tappeti afro-house. Un incontro magico tra l\'orizzonte del mare Adriatico e tradizioni nomadi antiche.',
    status: 'Tickets Available',
    priceRange: '€45 Regular',
    vibe: 'Ethnic Desert-Oasis, Tribal Percussions, Beach Fire',
    isFavorite: true,
    trackSample: {
      title: 'Fasano Shaman Chant',
      artist: 'Badawi Nomads',
      bpm: 123,
      genre: 'Organic House'
    }
  },
  {
    id: 'cocorico-exclusive',
    name: 'Cocoricò Pyramid Special',
    venue: 'Cocoricò Club',
    location: 'Riccione, Emilia-Romagna',
    coordinates: { x: 48, y: 40 },
    date: '22 Agosto 2026',
    timestamp: new Date('2026-08-22').getTime(),
    genre: 'Techno / Hard Groove',
    lineup: ['Ilario Alicante', 'Indira Paganotto', 'Marco Carola', 'Deborah De Luca', 'Cirillo', 'Saccomandi', 'Riki Binari'],
    description: 'Sotto la leggendaria piramide di vetro di Riccione, un party esclusivo "MEMBERZ ONLY" dedicato a chi vive la club culture più autentica. Uno show laser potenziato, fumo denso ed un muro di suono analogico unico in Europa.',
    status: 'Sold Out',
    priceRange: '€40 - €70',
    vibe: 'Laser Dome, Legendary Glass Pyramid, Raw Energy',
    trackSample: {
      title: 'Glow',
      artist: 'Ilario Alicante',
      bpm: 132,
      genre: 'Techno'
    }
  },
  {
    id: 'inota-festival',
    name: 'INOTA Power Plant Fest',
    venue: 'Inota Thermal Power Plant',
    location: 'Inota (Veszprém), Ungheria',
    coordinates: { x: 92, y: 12 },
    date: '27 - 30 Agosto 2026',
    timestamp: new Date('2026-08-27').getTime(),
    genre: 'Industrial Industrial / Techno',
    lineup: ['Nils Frahm', 'Max Cooper', 'Ben Klock', 'Dasha Rush', 'Daniel Avery', 'Kiasmos', 'KiNK'],
    description: 'Un festival visionario ospitato all\'interno di un imponente centrale termoelettrica sovietica dimessa in Ungheria, a solo un\'ora da Budapest. Le iconiche torri di raffreddamento iperboliche diventano maxischermi per proiezioni brutaliste e sound design sperimentale.',
    status: 'Tickets Available',
    priceRange: '€100 Pass',
    vibe: 'Brutalist Nuclear Gothic, Dynamic Projection, Cyberpunk',
    isInternational: true,
    trackSample: {
      title: 'Cooling Towers',
      artist: 'Inota Resident',
      bpm: 128,
      genre: 'Industrial Techno'
    }
  },
  {
    id: 'creamfields-uk',
    name: 'CREAMFIELDS Manchester',
    venue: 'Daresbury Estate',
    location: 'Daresbury, Regno Unito',
    coordinates: { x: 10, y: 12 },
    date: '28 - 29 Agosto 2026',
    timestamp: new Date('2026-08-28').getTime(),
    genre: 'EDM / Dance Crossover',
    lineup: ['Carl Cox', 'Faithless', 'Underworld', 'Fatboy Slim', 'Armin van Helden', 'Swedish House Mafia', 'Peggy Gou', 'Eric Prydz', 'David Guetta', 'Martin Garrix'],
    description: 'Il tempio sacro della musica dance globale a soli 30 minuti da Manchester. Creamfields richiama centinaia di migliaia di ravers sotto megastrutture d\'acciaio sormontate da incredibili fuochi d\'artificio, laser infiniti e i DJ più acclamati dello showbusiness mondiale.',
    status: 'Tickets Available',
    priceRange: '€180 (2 Days)',
    vibe: 'Colossal Steel Structure, Laser Skyline, Mainstage Rave',
    isFavorite: true,
    isInternational: true,
    trackSample: {
      title: 'Overdrive Manchester',
      artist: 'Creamfields DJ Group',
      bpm: 128,
      genre: 'EDM / Big Room'
    }
  },
  {
    id: 'decibel-jesolo',
    name: 'Decibel Open Air Showcase',
    venue: 'Jesolo Arena Concerti',
    location: 'Jesolo, Venezia',
    coordinates: { x: 46, y: 18 },
    date: '30 Agosto 2026',
    timestamp: new Date('2026-08-30').getTime(),
    genre: 'Electronic Crossover / Deep Tech',
    lineup: ['Peggy Gou', 'Amelie Lens', 'Boris Brejcha', 'Maceo Plex', 'Marco Faraone', '999999999', 'I Hate Models', 'Indira Paganotto'],
    description: 'Il gran finale dell\'estate 2026. Decibel Open Air unisce i migliori pesi massimi della musica consolle mondiale in una maxi arena alle porte di Venezia. Un tripudio di bassi e design scenografico d\'avanguardia.',
    status: 'Tickets Available',
    priceRange: '€55 - €90',
    vibe: 'Massive Crowd, Day Festival, Heavy Sound System',
    trackSample: {
      title: 'It Makes You Forget',
      artist: 'Peggy Gou',
      bpm: 125,
      genre: 'House'
    }
  },
  {
    id: 'polifonic-puglia',
    name: 'Polifonic Puglia 2026',
    venue: 'Masseria Capece & Cala Maka',
    location: 'Cisternino & Savelletri, Puglia',
    coordinates: { x: 74, y: 76 },
    date: '23 - 26 Luglio 2026',
    timestamp: new Date('2026-07-23').getTime(),
    genre: 'Deep House / Techno / Italo Disco',
    lineup: ['Gerd Janson', 'Hunee', 'Marie Davidson', 'Palms Trax', 'Bicep (DJ Set)', 'Francesco Del Garda', 'Z.I.P.P.O', 'DJ Koze', 'Call Super'],
    description: 'L\'esperienza sensoriale iconica della Puglia ritorna a risvegliare i sensi. Polifonic fonde architettura tradicional, gastronomia d\'eccellenza e una selezione artistica internazionale raffinata tra masserie fortificate e spiagge sabbiose.',
    status: 'Selling Fast',
    priceRange: '€95 Pass',
    vibe: 'Chic Aesthetic, Mediterranean Soundscape, Multi-Stage',
    trackSample: {
      title: 'Italo Flight',
      artist: 'Gerd Janson',
      bpm: 122,
      genre: 'Italo Disco'
    }
  },
  {
    id: 'panorama-festival',
    name: 'Panorama Festival 2026',
    venue: 'Parco Gondar & Monopoli Arena',
    location: 'Gallipoli & Monopoli, Puglia',
    coordinates: { x: 79, y: 89 },
    date: '12 - 16 Agosto 2026',
    timestamp: new Date('2026-08-12').getTime(),
    genre: 'Melodic Techno / Heavy Techno',
    lineup: ['Peggy Gou', 'Charlotte de Witte', 'Adriatique', 'Mochakk', 'Solomun', 'The Blessed Madonna', 'Jamie Jones', 'PAWSA', 'Loco Dice', 'Marco Carola'],
    description: 'Il festival elettronico gigante del Sud Italia. Cinque giorni di pura energia con i pesi massimi mondiali della scena house e techno distribuiti tra arene all\'aperto e affascinanti masserie immerse nella campagna pugliese.',
    status: 'Tickets Available',
    priceRange: '€110 Full Pass',
    vibe: 'Massive Production, Open Big Stage, High Energy Rave',
    trackSample: {
      title: 'Miracle Salento',
      artist: 'Adriatique',
      bpm: 124,
      genre: 'Melodic Techno'
    }
  },
  {
    id: 'cala-mariposa',
    name: 'Cala Mariposa Vibes 2026',
    venue: 'Cala Mariposa Resort',
    location: 'Polignano a Mare, Puglia',
    coordinates: { x: 73, y: 71 },
    date: '09 Agosto 2026',
    timestamp: new Date('2026-08-09').getTime(),
    genre: 'Afro House / Organic Lounge',
    lineup: ['Keinemusik (Rampa & &ME & Adam Port)', 'Amémé', 'Local Talents', 'Pablo Fierro', 'Themba', 'Laolu', 'Salento Roots'],
    description: 'Un party esclusivo sulla scogliera bianca di Polignano. Cala Mariposa celebra l\'estate pugliese con i caldi ritmi afro-house e percussioni sincopate, il tutto mentre il sole tramonta nell\'azzurro del mare Adriatico.',
    status: 'Selling Fast',
    priceRange: '€50 Entry',
    vibe: 'Cliffside Sunset, Chic Crowds, Afro House Grooves',
    trackSample: {
      title: 'Mariposa Sunset',
      artist: 'Keinemusik',
      bpm: 120,
      genre: 'Afro House'
    }
  },
  {
    id: 'clorophilla-club',
    name: 'Clorophilla Forest Rave',
    venue: 'Clorophilla Club',
    location: 'Castellaneta Marina (Taranto), Puglia',
    coordinates: { x: 70, y: 79 },
    date: '15 Agosto 2026',
    timestamp: new Date('2026-08-15').getTime(),
    genre: 'Psychedelic Techno / Progressive House',
    lineup: ['Maceo Plex', 'Mind Against', 'Recondite (Live)', 'Tale Of Us', 'Fideles', 'Dino Lenny', 'Forest Goblins'],
    description: 'Il tempio verde del clubbing meridionale. Clorophilla è una discoteca all\'aperto immersa in una fittissima pineta protetta, dove la musica si fonde con la natura incontaminata in un tripudio di laser verdi, fumo e pura connessione terrestre.',
    status: 'Tickets Available',
    priceRange: '€40 Space',
    vibe: 'Deep Pine Forest, Intense Lasers, Underground Rave',
    trackSample: {
      title: 'Deep Woods',
      artist: 'Mind Against',
      bpm: 123,
      genre: 'Melodic Techno'
    }
  },
  {
    id: 'the-sanctuary-itria',
    name: 'The Sanctuary Itria Valley',
    venue: 'The Sanctuary Oasis',
    location: 'Ostuni (Brindisi), Puglia',
    coordinates: { x: 75, y: 76 },
    date: '19 Agosto 2026',
    timestamp: new Date('2026-08-19').getTime(),
    genre: 'Organic Slow House / Downtempo',
    lineup: ['Sven Väth (Ambient Set)', 'Satori', 'Valle d\'Itria Shamans', 'Goldcap', 'Sabo', 'Be Svendsen'],
    description: 'Un rifugio olistico e musicale immerso tra fichi d\'India e ulivi millenari nella bianca Ostuni. Un rituale di guarigione acustica che fonde sonorità tribali lente, cibo organico, mercatini di artigianato locale ed installazioni scenografiche eteree.',
    status: 'Tickets Available',
    priceRange: '€35 Entry',
    vibe: 'Holistic Oasis, Slow Rave, Organic Decor, Sacred Fire',
    trackSample: {
      title: 'Ostuni Shamanism',
      artist: 'Satori',
      bpm: 115,
      genre: 'Downtempo'
    }
  },
  {
    id: 'sacro-puglia',
    name: 'SACRO Puglia Ritual',
    venue: 'Castello Ducale Ceglie',
    location: 'Ceglie Messapica, Puglia',
    coordinates: { x: 74, y: 78 },
    date: '28 Agosto 2026',
    timestamp: new Date('2026-08-28').getTime(),
    genre: 'Melodic Techno / Neo-Classical Electronic',
    lineup: ['Stephan Bodzin (Live)', 'Christian Löffler', 'Kiasmos', 'HVOB', 'Jan Blomqvist', 'Cercle DJ'],
    description: 'Un rituale mistico ospitato tra le possenti mura storiche di Ceglie Messapica. SACRO fonde la maestosità della pietra medievale, proiezioni monumentali 3D e performance musicali dal vivo emotivamente cariche di melodia ed eleganza.',
    status: 'Selling Fast',
    priceRange: '€45 Pass',
    vibe: 'Medieval Castle, 3D Monumental Projections, Pure Melodic',
    trackSample: {
      title: 'Ducale Echo',
      artist: 'Stephan Bodzin',
      bpm: 124,
      genre: 'Melodic Techno'
    }
  },
  {
    id: 'mandarino-club',
    name: 'Mandarino Club Special',
    venue: 'Mandarino Club',
    location: 'Ginosa (Taranto), Puglia',
    coordinates: { x: 70, y: 76 },
    date: '16 Agosto 2026',
    timestamp: new Date('2026-08-16').getTime(),
    genre: 'Deep Tech / Tech House',
    lineup: ['Jamie Jones', 'The Martinez Brothers', 'Enzo Siragusa', 'Richy Ahmed', 'wAFF', 'Skream', 'Rossi.'],
    description: 'L\'iconico club tarantino celebra il picco dell\'estate con un party notturno all\'aperto. Sotto le fronde delle folte pinete e a pochi passi dalle spiagge ioniche, dandy e clubber si riuniscono per ballare fino all\'alba.',
    status: 'Tickets Available',
    priceRange: '€35 Regular',
    vibe: 'Open-Air Forest Club, Ionic Coast Ibiza Style',
    trackSample: {
      title: 'Mandarino Tech',
      artist: 'Jamie Jones',
      bpm: 126,
      genre: 'Tech House'
    }
  },
  {
    id: 'plaza-bay',
    name: 'Plaza Bay Beach Party',
    venue: 'Plaza Bay Beach Club',
    location: 'Barletta, Puglia',
    coordinates: { x: 71, y: 65 },
    date: '10 Agosto 2026',
    timestamp: new Date('2026-08-10').getTime(),
    genre: 'Melodic House / Afro Grooves',
    lineup: ['Black Coffee', 'Shimza', 'Bari Selectors', 'Culoe De Song', 'Da Capo', 'Themba', 'Adriatic Roots'],
    description: 'Un sofisticato beach party sulla costa adriatica a Barletta. Ottimo sound system, drink premium, decoro bohémien e un set dal giorno alla sera guidato dai pionieri dell\'Afro House mondiale.',
    status: 'Selling Fast',
    priceRange: '€40 All Inclusive',
    vibe: 'Sandy Beach Club, Bohémien Decor, Afro Beats',
    trackSample: {
      title: 'Adriatic Dawn',
      artist: 'Black Coffee',
      bpm: 121,
      genre: 'Afro House'
    }
  },
  {
    id: 'nextones-fest',
    name: 'Nextones Festival 2026',
    venue: 'Teatro di Pietra (Cava di San Giovanni)',
    location: 'Val d’Ossola, Piemonte',
    coordinates: { x: 22, y: 15 },
    date: '16 - 19 Luglio 2026',
    timestamp: new Date('2026-07-16').getTime(),
    genre: 'AV Electronic / Ambient / Experimental',
    lineup: ['Caterina Barbieri', 'Ben Frost', 'Robert Henke', 'A/V Live Performance', 'Tim Hecker', 'Oneohtrix Point Never', 'Kali Malone'],
    description: 'International Festival for Sonic and Landscape Explorations. A unique artistic celebration nestled between the massive rock walls of Val d\'Ossola, designed to co-exist with the majestic natural landscapes of the Piedmontese alpine region.',
    status: 'Tickets Available',
    priceRange: '€110 All Pass',
    vibe: 'Alpine Gneiss Quarry, High Tech A/V Installations, Sound Research',
    isInternational: false,
    trackSample: {
      title: 'Fantas',
      artist: 'Caterina Barbieri',
      bpm: 120,
      genre: 'Modular Synthesizer'
    }
  },
  {
    id: 'selectors-croatia',
    name: 'Dekmantel Selectors 2026',
    venue: 'The Garden Tisno',
    location: 'Tisno, Croazia',
    coordinates: { x: 88, y: 48 },
    date: '20 - 24 Agosto 2026',
    timestamp: new Date('2026-08-20').getTime(),
    genre: 'House / Disco / Leftfield Electro',
    lineup: ['Hunee', 'Palms Trax', 'Young Marco', 'Antal', 'Elena Colombi', 'Carista', 'Objekt', 'Ben UFO', 'Dekmantel Soundsystem'],
    description: 'Il rinomato spin-off estivo di Dekmantel sull\'Adriatico a Tisno. Celebre per i suoi intimi boat parties baciati dal tramonto croato e set carichi di gemme musicali rare selezionate dai digger più rigorosi.',
    status: 'Tickets Available',
    priceRange: '€195 All Pass',
    vibe: 'Tisno Beach Rave, Adriatic Boat Parties, Rare Grooves',
    isInternational: true,
    ticketLink: 'https://www.dekmantel.com/selectors',
    trackSample: {
      title: 'Tisno Sunset Waves',
      artist: 'Selectors Group',
      bpm: 118,
      genre: 'Warm House'
    }
  },
  {
    id: 'butik-slovenia',
    name: 'BUTIK Festival 2026',
    venue: 'Soča Valley Woods & River',
    location: 'Tolmin, Slovenia',
    coordinates: { x: 62, y: 15 },
    date: '09 - 12 Luglio 2026',
    timestamp: new Date('2026-07-09').getTime(),
    genre: 'Minimal / Deep Techno',
    lineup: ['RPR Collectif', 'Jane Fitz', 'Margaret Dygas', 'River Stage Residents', 'Praslea', 'Raresh', 'Petre Inspirescu', 'Rhadoo'],
    description: 'Un piccolo paradiso immerso nella folta foresta della suggestiva Valle dell\'Isonzo. Butik vanta una lineup di stampo minimal ricercato ed un\'atmosfera incredibilmente conviviale a bordo del caratteristico fiume turchese.',
    status: 'Tickets Available',
    priceRange: '€130 Festival Pass',
    vibe: 'Slovenian Pines, Cold Turquoise River Dips, Intimate Minimal',
    isInternational: true,
    trackSample: {
      title: 'Soča Breeze',
      artist: 'Tolmin Live Set',
      bpm: 124,
      genre: 'Minimal Techno'
    }
  },
  {
    id: 'waking-life',
    name: 'Waking Life 2026',
    venue: 'Lake Shore Oasis',
    location: 'Crato, Alentejo, Portogallo',
    coordinates: { x: 10, y: 80 },
    date: '19 - 24 Agosto 2026',
    timestamp: new Date('2026-08-19').getTime(),
    genre: 'Hypnotic Electro / Downtempo / Ambient',
    lineup: ['Map.ache', 'Rhadoo', 'Luigi Tozzi (Live)', 'Vessel', 'Sebastian Mullaert', 'Giegling Crew', 'Edward', 'Konstantin'],
    description: 'Un rituale festivaliero trasformativo tenuto a Crato, sulle sponde selvagge di un placido lago nell\'Alentejo portoghese. Un incontro magico tra sound curatissimi, installazioni terrestri fluttuanti e pratiche ecologiche attive.',
    status: 'Selling Fast',
    priceRange: '€220 Full Pass',
    vibe: 'Floating Lake Sculptures, Desert Magic, Transformative Co-creation',
    isInternational: true,
    trackSample: {
      title: 'Lago Fluttuante',
      artist: 'Rhadoo Mix',
      bpm: 122,
      genre: 'Hypnotic Techno'
    }
  },
  {
    id: 'dekmantel-amsterdam',
    name: 'DEKMANTEL Festival 2026',
    venue: 'Amsterdamse Bos',
    location: 'Amsterdam, Paesi Bassi',
    coordinates: { x: 35, y: 10 },
    date: '05 - 09 Agosto 2026',
    timestamp: new Date('2026-08-05').getTime(),
    genre: 'Avant-garde Techno / House / Electro',
    lineup: ['Jeff Mills', 'Helena Hauff', 'Ben UFO', 'Joy Orbison', 'Floating Points', 'Palms Trax', 'Marcel Dettmann', 'Sherelle', 'LTC'],
    description: 'La vera Mecca planetaria per gli amanti della musica elettronica sotterranea e d\'avanguardia, dislocata tra gli alberi centenari della foresta monumentale di Amsterdam. Una celebrazione leggendaria della ricerca sonora globale.',
    status: 'Tickets Available',
    priceRange: '€240 5-day Pass',
    isFavorite: true,
    vibe: 'Amsterdam Forest Canopy, Avant-garde Electronic, High Fidelity Systems',
    isInternational: true,
    trackSample: {
      title: 'Bos Resonance',
      artist: 'Ben UFO Set',
      bpm: 128,
      genre: 'UK Bass / Electro'
    }
  },
  {
    id: 'monegros-desert-festival',
    name: 'Monegros Desert Festival 2026',
    venue: 'Fraga (Huesca) Desert',
    location: 'Fraga, Spagna',
    coordinates: { x: 28, y: 55 },
    date: '25 Luglio 2026',
    timestamp: new Date('2026-07-25').getTime(),
    genre: 'Techno / Hard Techno / Drum & Bass / Hip Hop',
    lineup: ['Amelie Lens', 'Andrés Campo', 'Paco Osuna', 'Paul Kalkbrenner', '999999999', 'I Hate Models', 'Adam Beyer', 'Richie Hawtin', 'Vitalic', 'Wu-Tang Clan'],
    description: 'Il festival elettronico sotterraneo più famoso ed estremo d’Europa nel deserto di Fraga in Spagna. Una spettacolare celebrazione non-stop di 24 ore che unisce oltre 50.000 ravers sotto il sole bollente e le stelle del deserto, supportati da gigantesche stage artistiche e una produzione audio monumentale.',
    status: 'Tickets Available',
    priceRange: '€95 - €135',
    vibe: 'Extreme Desert Rave, 24h Non-Stop, Monumental Audio Systems',
    isInternational: true,
    trackSample: {
      title: 'Desert Wind Techno',
      artist: 'Andrés Campo',
      bpm: 142,
      genre: 'Hard Techno'
    }
  }
];
